name: openblock
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch
  - torchvision
  - numpy>=1.20.0
  - opencv-python>=4.5.0
  - matplotlib>=3.4.0
  - pyyaml>=5.4.0
  - rich>=10.0.0
  - pip:
    - mmcv>=2.0.0
    - mmengine>=0.7.1
    - mmdet>=3.1.0
    - mmpretrain>=1.0.0
    - mmyolo>=0.6.0
    - tensorboard>=2.5.0
    - wandb>=0.12.0
    - onnx>=1.9.0
    - onnxruntime>=1.8.0 